### ISSUE TITLE
same color coding of tags as on datatracker.ietf.org

### ISSUE THREAD

**Issue by wodny** [mnot/rfc.fyi#22]
I think it might be useful to have the same color codes for tags as on [datatracker]:
![image](https://user-images.githubusercontent.com/882353/120312820-7dd90b00-c2d9-11eb-8fd4-d86d7220737f.png)

From site's source (reordered):
```css
.bgwhite  { background-color: white; }
.bgred    { background-color: #F44; }
.bgorange { background-color: #FA0; }
.bgyellow { background-color: #EE0; }
.bgmagenta{ background-color: #F4F; }
.bgblue   { background-color: #66F; }
.bgcyan   { background-color: #4DD; }
.bggreen  { background-color: #4F4; }
.bggrey   { background-color: #666; }
.bgbrown  { background-color: #840; }
```
[datatracker]: https://datatracker.ietf.org/doc/html/rfc6750
